In [23]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import math,time,random,datetime
import seaborn as sns

In [24]:
train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')

In [25]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
x_train=train_data.drop(['Survived'],axis=1)

In [27]:
x_train.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
y_train=train_data[['Survived']]

In [29]:
y_train.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [30]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [31]:
gsd=pd.read_csv('gender_submission.csv')

In [32]:
gsd.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [33]:
train_data.shape

(891, 12)

In [34]:
test_data.shape

(418, 11)

In [35]:
gsd.shape

(418, 2)

In [38]:
x_train.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
x_train.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [39]:
x_train.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
titanic = train_data.append(test_data)
# create indexes to separate data later on
train_idx = len(train_data)
test_idx = len(titanic)-len(test_data)

In [43]:
titanic.shape

(1309, 12)

In [44]:
titanic['Title'] = titanic.Name.apply(lambda name: name.split(',')[1].split('.')[0].strip())

In [46]:
normalized_titles = {
    "Capt":       "Officer",
    "Col":        "Officer",
    "Major":      "Officer",
    "Jonkheer":   "Royalty",
    "Don":        "Royalty",
    "Sir" :       "Royalty",
    "Dr":         "Officer",
    "Rev":        "Officer",
    "the Countess":"Royalty",
    "Dona":       "Royalty",
    "Mme":        "Mrs",
    "Mlle":       "Miss",
    "Ms":         "Mrs",
    "Mr" :        "Mr",
    "Mrs" :       "Mrs",
    "Miss" :      "Miss",
    "Master" :    "Master",
    "Lady" :      "Royalty"
}
# map the normalized titles to the current titles 
titanic.Title = titanic.Title.map(normalized_titles)
# view value counts for the normalized titles
print(titanic.Title.value_counts())

Mr         757
Miss       262
Mrs        200
Master      61
Officer     23
Royalty      6
Name: Title, dtype: int64

In [47]:
# group by Sex, Pclass, and Title 
grouped = titanic.groupby(['Sex','Pclass', 'Title'])  
# view the median Age by the grouped features 
grouped.Age.median()

Sex     Pclass  Title
female  1       Miss       30.0
                Mrs        45.0
                Officer    49.0
                Royalty    39.0
        2       Miss       20.0
                Mrs        30.0
        3       Miss       18.0
                Mrs        31.0
male    1       Master      6.0
                Mr         41.5
                Officer    52.0
                Royalty    40.0
        2       Master      2.0
                Mr         30.0
                Officer    41.5
        3       Master      6.0
                Mr         26.0
Name: Age, dtype: float64

In [79]:
grouped.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket,Title,FamilySize
0,22.00,U,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,0,1,0.0,A/5 21171,Mr,2
1,38.00,C,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,1,1,1.0,PC 17599,Mrs,2
2,26.00,U,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,1,0,1.0,STON/O2. 3101282,Miss,1
3,35.00,C,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,1,1,1.0,113803,Mrs,2
4,35.00,U,S,8.0500,"Allen, Mr. William Henry",0,5,3,0,0,0.0,373450,Mr,1
5,NaN,U,Q,8.4583,"Moran, Mr. James",0,6,3,0,0,0.0,330877,Mr,1
6,54.00,E,S,51.8625,"McCarthy, Mr. Timothy J",0,7,1,0,0,0.0,17463,Mr,1
7,2.00,U,S,21.0750,"Palsson, Master. Gosta Leonard",1,8,3,0,3,0.0,349909,Master,5
8,27.00,U,S,11.1333,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",2,9,3,1,0,1.0,347742,Mrs,3
9,14.00,U,C,30.0708,"Nasser, Mrs. Nicholas (Adele Achem)",0,10,2,1,1,1.0,237736,Mrs,2
10,4.00,G,S,16.7000,"Sandstrom, Miss. Marguerite Rut",1,11,3,1,1,1.0,PP 9549,Miss,3
11,58.00,C,S,26.5500,"Bonnell, Miss. Elizabeth",0,12,1,1,0,1.0,113783,Miss,1
12,20.00,U,S,8.0500,"Saundercock, Mr. William Henry",0,13,3,0,0,0.0,A/5. 2151,Mr,1
13,39.00,U,S,31.2750,"Andersson, Mr. Anders Johan",5,14,3,0,1,0.0,347082,Mr,7
14,14.00,U,S,7.8542,"Vestrom, Miss. Hulda Amanda Adolfina",0,15,3,1,0,0.0,350406,Miss,1
15,55.00,U,S,16.0000,"Hewlett, Mrs. (Mary D Kingcome)",0,16,2,1,0,1.0,248706,Mrs,1
16,2.00,U,Q,29.1250,"Rice, Master. Eugene",1,17,3,0,4,0.0,382652,Master,6
17,NaN,U,S,13.0000,"Williams, Mr. Charles Eugene",0,18,2,0,0,1.0,244373,Mr,1
18,31.00,U,S,18.0000,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",0,19,3,1,1,0.0,345763,Mrs,2
19,NaN,U,C,7.2250,"Masselmani, Mrs. Fatima",0,20,3,1,0,1.0,2649,Mrs,1
20,35.00,U,S,26.0000,"Fynney, Mr. Joseph J",0,21,2,0,0,0.0,239865,Mr,1
21,34.00,D,S,13.0000,"Beesley, Mr. Lawrence",0,22,2,0,0,1.0,248698,Mr,1
22,15.00,U,Q,8.0292,"McGowan, Miss. Anna ""Annie""",0,23,3,1,0,1.0,330923,Miss,1
23,28.00,A,S,35.5000,"Sloper, Mr. William Thompson",0,24,1,0,0,1.0,113788,Mr,1
24,8.00,U,S,21.0750,"Palsson, Miss. Torborg Danira",1,25,3,1,3,0.0,349909,Miss,5
25,38.00,U,S,31.3875,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",5,26,3,1,1,1.0,347077,Mrs,7
27,19.00,C,S,263.0000,"Fortune, Mr. Charles Alexander",2,28,1,0,3,0.0,19950,Mr,6
30,40.00,U,C,27.7208,"Uruchurtu, Don. Manuel E",0,31,1,0,0,0.0,PC 17601,Royalty,1
31,NaN,B,C,146.5208,"Spencer, Mrs. William Augustus (Marie Eugenie)",0,32,1,1,1,1.0,PC 17569,Mrs,2
33,66.00,U,S,10.5000,"Wheadon, Mr. Edward H",0,34,2,0,0,0.0,C.A. 24579,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,23.00,C,S,263.0000,"Fortune, Miss. Mabel Helen",2,89,1,1,3,1.0,19950,Miss,6
123,32.50,E,S,13.0000,"Webber, Miss. Susan",0,124,2,1,0,1.0,27267,Miss,1
136,19.00,D,S,26.2833,"Newsom, Miss. Helen Monypeny",2,137,1,1,0,1.0,11752,Miss,3
149,42.00,U,S,13.0000,"Byles, Rev. Thomas Roussel Davids",0,150,2,0,0,0.0,244310,Officer,1
150,51.00,U,S,12.5250,"Bateman, Rev. Robert James",0,151,2,0,0,0.0,S.O.P. 1166,Officer,1
151,22.00,C,S,66.6000,"Pears, Mrs. Thomas (Edith Wearne)",0,152,1,1,1,1.0,113776,Mrs,2
177,50.00,C,C,28.7125,"Isham, Miss. Ann Elizabeth",0,178,1,1,0,0.0,PC 17595,Miss,1
183,1.00,F,S,39.0000,"Becker, Master. Richard F",1,184,2,0,2,1.0,230136,Master,4
193,3.00,F,S,26.0000,"Navratil, Master. Michel M",1,194,2,0,1,1.0,230080,Master,3
245,44.00,C,Q,90.0000,"Minahan, Dr. William Edward",0,246,1,0,2,0.0,19928,Officer,3
249,54.00,U,S,26.0000,"Carter, Rev. Ernest Courtenay",0,250,2,0,1,0.0,244252,Officer,2
305,0.92,C,S,151.5500,"Allison, Master. Hudson Trevor",2,306,1,0,1,1.0,113781,Master,4
317,54.00,U,S,14.0000,"Moraweck, Dr. Ernest",0,318,2,0,0,0.0,29011,Officer,1
340,2.00,F,S,26.0000,"Navratil, Master. Edmond Roger",1,341,2,0,1,1.0,230080,Master,3
398,23.00,U,S,10.5000,"Pain, Dr. Alfred",0,399,2,0,0,0.0,244278,Officer,1
407,3.00,U,S,18.7500,"Richards, Master. William Rowe",1,408,2,0,1,1.0,29106,Master,3
445,4.00,A,S,81.8583,"Dodge, Master. Washington",2,446,1,0,0,1.0,33638,Master,3
449,52.00,C,S,30.5000,"Peuchen, Major. Arthur Godfrey",0,450,1,0,0,1.0,113786,Officer,1
536,45.00,B,S,26.5500,"Butt, Major. Archibald Willingham",0,537,1,0,0,0.0,113050,Officer,1
556,48.00,A,C,39.6000,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",0,557,1,1,1,1.0,11755,Royalty,2
599,49.00,A,C,56.9292,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",0,600,1,0,1,1.0,PC 17485,Royalty,2
632,32.00,B,C,30.5000,"Stahelin-Maeglin, Dr. Max",0,633,1,0,0,1.0,13214,Officer,1
647,56.00,A,C,35.5000,"Simonius-Blumer, Col. Oberst Alfons",0,648,1,0,0,1.0,13213,Officer,1
759,33.00,B,S,86.5000,"Rothes, the Countess. of (Lucy Noel Martha Dye...",0,760,1,1,0,1.0,110152,Royalty,1
796,49.00,D,S,25.9292,"Leader, Dr. Alice (Farnham)",0,797,1,1,0,1.0,17465,Officer,1
802,11.00,B,S,120.0000,"Carter, Master. William Thornton II",2,803,1,0,1,1.0,113760,Master,4
822,38.00,U,S,0.0000,"Reuchlin, Jonkheer. John George",0,823,1,0,0,0.0,19972,Royalty,1
64,13.00,B,C,262.3750,"Ryerson, Master. John Borie",2,956,1,0,2,NaN,PC 17608,Master,5
196,6.00,E,C,134.5000,"Spedden, Master. Robert Douglas",2,1088,1,0,0,NaN,16966,Master,3
414,39.00,C,C,108.9000,"Oliva y Ocana, Dona. Fermina",0,1306,1,1,0,NaN,PC 17758,Royalty,1

In [99]:
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [97]:
titanic.join(grouped['Age'])

TypeError: Can only merge Series or DataFrame objects, a <class 'pandas.core.groupby.generic.SeriesGroupBy'> was passed

In [52]:
titanic.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket,Title
0,22.0,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0.0,A/5 21171,Mr
1,38.0,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1.0,PC 17599,Mrs
2,26.0,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1.0,STON/O2. 3101282,Miss
3,35.0,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1.0,113803,Mrs
4,35.0,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0.0,373450,Mr

In [75]:
titanic.isnull().sum()

Age            263
Cabin            0
Embarked         0
Fare             0
Name             0
Parch            0
PassengerId      0
Pclass           0
Sex              0
SibSp            0
Survived       418
Ticket           0
Title            0
FamilySize       0
dtype: int64

In [54]:
# fill Cabin NaN with U for unknown
titanic.Cabin = titanic.Cabin.fillna('U')
# find most frequent Embarked value and store in variable
most_embarked = titanic.Embarked.value_counts().index[0]

# fill NaN with most_embarked value
titanic.Embarked = titanic.Embarked.fillna(most_embarked)
# fill NaN with median fare
titanic.Fare = titanic.Fare.fillna(titanic.Fare.median())

# view changes
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 13 columns):
Age            1046 non-null float64
Cabin          1309 non-null object
Embarked       1309 non-null object
Fare           1309 non-null float64
Name           1309 non-null object
Parch          1309 non-null int64
PassengerId    1309 non-null int64
Pclass         1309 non-null int64
Sex            1309 non-null object
SibSp          1309 non-null int64
Survived       891 non-null float64
Ticket         1309 non-null object
Title          1309 non-null object
dtypes: float64(3), int64(4), object(6)
memory usage: 143.2+ KB

In [55]:
# size of families (including the passenger)
titanic['FamilySize'] = titanic.Parch + titanic.SibSp + 1

In [56]:
# map first letter of cabin to itself
titanic.Cabin = titanic.Cabin.map(lambda x: x[0])

In [57]:
titanic.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket,Title,FamilySize
0,22.0,U,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0.0,A/5 21171,Mr,2
1,38.0,C,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1.0,PC 17599,Mrs,2
2,26.0,U,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1.0,STON/O2. 3101282,Miss,1
3,35.0,C,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1.0,113803,Mrs,2
4,35.0,U,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0.0,373450,Mr,1

In [58]:
# Convert the male and female groups to integer form
titanic.Sex = titanic.Sex.map({"male": 0, "female":1})
# create dummy variables for categorical features
pclass_dummies = pd.get_dummies(titanic.Pclass, prefix="Pclass")
title_dummies = pd.get_dummies(titanic.Title, prefix="Title")
cabin_dummies = pd.get_dummies(titanic.Cabin, prefix="Cabin")
embarked_dummies = pd.get_dummies(titanic.Embarked, prefix="Embarked")
# concatenate dummy columns with main dataset
titanic_dummies = pd.concat([titanic, pclass_dummies, title_dummies, cabin_dummies, embarked_dummies], axis=1)

# drop categorical fields
titanic_dummies.drop(['Pclass', 'Title', 'Cabin', 'Embarked', 'Name', 'Ticket'], axis=1, inplace=True)

titanic_dummies.head()

,Age,Fare,Parch,PassengerId,Sex,SibSp,Survived,FamilySize,Pclass_1,Pclass_2,...,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_U,Embarked_C,Embarked_Q,Embarked_S
0,22.0,7.2500,0,1,0,1,0.0,2,0,0,...,0,0,0,0,0,0,1,0,0,1
1,38.0,71.2833,0,2,1,1,1.0,2,1,0,...,1,0,0,0,0,0,0,1,0,0
2,26.0,7.9250,0,3,1,0,1.0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,35.0,53.1000,0,4,1,1,1.0,2,1,0,...,1,0,0,0,0,0,0,0,0,1
4,35.0,8.0500,0,5,0,0,0.0,1,0,0,...,0,0,0,0,0,0,1,0,0,1

In [90]:
titanic_dummies.isnull().sum()

Age              263
Fare               0
Parch              0
PassengerId        0
Sex                0
SibSp              0
Survived         418
FamilySize         0
Pclass_1           0
Pclass_2           0
Pclass_3           0
Title_Master       0
Title_Miss         0
Title_Mr           0
Title_Mrs          0
Title_Officer      0
Title_Royalty      0
Cabin_A            0
Cabin_B            0
Cabin_C            0
Cabin_D            0
Cabin_E            0
Cabin_F            0
Cabin_G            0
Cabin_T            0
Cabin_U            0
Embarked_C         0
Embarked_Q         0
Embarked_S         0
dtype: int64

In [59]:
# create train and test data
train = titanic_dummies[ :train_idx]
test = titanic_dummies[test_idx: ]

# convert Survived back to int
train.Survived = train.Survived.astype(int)
# create X and y for data and target values 
X = train.drop('Survived', axis=1).values 
y = train.Survived.values
# create array for test set
X_test = test.drop('Survived', axis=1).values

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [60]:
# create param grid object 
forrest_params = dict(     
    max_depth = [n for n in range(9, 14)],     
    min_samples_split = [n for n in range(4, 11)], 
    min_samples_leaf = [n for n in range(2, 5)],     
    n_estimators = [n for n in range(10, 60, 10)],
)

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV

In [67]:
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X, y)
y_pred = random_forest.predict(X_test)
random_forest.score(X_test,y_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').